 version: "3.0"
 
 services:
    web:        
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - /e/Worker/Docker/DockerGuide/frontend:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
    tests:        
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - /e/Worker/Docker/DockerGuide/frontend:/app
        command: ["npm", "run", "test"]
